version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "9000:9000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      NODE_ENV: development
      PORT: 9000
      DEV_DB_USERNAME: postgres
      DEV_DB_PASSWORD: postgres
      DEV_DB_NAME: pokedex
      DEV_DB_HOSTNAME: postgres
      DEV_DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_TTL: 3600
      WEATHER_API_KEY: 7b7048a95c0160c9b69a853ee70506cc
      WEATHER_API_URL: https://api.openweathermap.org/data/2.5/weather
      DEFAULT_LATITUDE: 48.8566
      DEFAULT_LONGITUDE: 2.3522
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "sleep 10 && npm run db:migrate && npm run db:seed && npm run dev"

volumes:
  postgres_data:
  redis_data:

