version: '3.8'

# PRODUCTION - Monitoring Stack
# Ce fichier est pour le serveur de monitoring (hôte séparé)
# Il scrape les métriques depuis les serveurs d'application distants

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_prod
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./configs/monitoring/prometheus-prod.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://monitoring.votredomaine.com
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring_network

  # Optionnel : Alertmanager pour les alertes
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager_prod
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./configs/monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

